
wechat:
  appid: wx6147ae9b7dd5541f
  appsecret: e087cf6501d841f53b75076e6d6f928e
  token:
    url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${wechat.appid}&secret=${wechat.appsecret}
  send:
    message: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=
    templateId: mXeot71tSnVPcl96FQAYFcEbe1V07uFcYQZ4xYib8tc
    toUser: opc9-6dau3sPq0cI9YKRbwci-eYM # opc9-6dau3sPq0cI9YKRbwci-eYM opc9-6a01s7z46uYoh8VP1RV-MBw
  create:
    menu: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=
  upload:
    file: https://api.weixin.qq.com/cgi-bin/material/add_material?access_token=
  get:
    mediaList: https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token=

  access:
    token: 6dau3sPq0cI9YKRbwci
  imge: wNFKAvg_badI-zsrsDgpQKhYaYoi-EHElZFuAv-DRO4u3N9lCb3J1ted7fPo105t
  video: wNFKAvg_badI-zsrsDgpQP_OwziDXgdbwS_EzObC4GMG53l1sjzVC_3Xxdv9Qc-y

hf:
  location: 123.41,41.82
  weather:
    url: https://devapi.qweather.com/v7/weather/now?location=${hf.location}&key=${hf.key}
  key: 1b2ea129968d4573a566ecb8874a2662

holiday:
  url: http://timor.tech/api/holiday/year/


#配置日志
logging:
  config: classpath:logback-spring.xml